// <auto-generated />
using System;
using Inventory.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventory.API.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260409160000_RemoveVarietyColumnsFromItem")]
    partial class RemoveVarietyColumnsFromItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inventory.API.Data.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("AggregateId")
                        .HasDatabaseName("ix_audit_log_aggregate_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_log_occurred_at");

                    b.HasIndex("OutboxId")
                        .IsUnique()
                        .HasDatabaseName("ix_audit_log_outbox_id");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_category_owner_id");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryAvailability", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("DisplayTimes")
                        .HasColumnType("text")
                        .HasColumnName("display_times");

                    b.Property<string>("InventoryItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inventory_item_id");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<string>("OpeningDayHours")
                        .HasColumnType("text")
                        .HasColumnName("opening_day_hours");

                    b.Property<bool>("OutOfStock")
                        .HasColumnType("boolean")
                        .HasColumnName("out_of_stock");

                    b.Property<DateTimeOffset?>("OutOfStockUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("out_of_stock_updated_at");

                    b.Property<string>("OutOfStockUpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("out_of_stock_updated_by");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<bool>("ScheduleAhead")
                        .HasColumnType("boolean")
                        .HasColumnName("schedule_ahead");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("stock_quantity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_inventory_availability");

                    b.HasIndex("InventoryItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_availability_inventory_item_id");

                    b.ToTable("inventory_availability", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal?>("AdditionalDeliveryFee")
                        .HasColumnType("numeric")
                        .HasColumnName("additional_delivery_fee");

                    b.Property<string>("AdditionalDeliveryFeeDescription")
                        .HasColumnType("text")
                        .HasColumnName("additional_delivery_fee_description");

                    b.Property<string>("Attributes")
                        .HasColumnType("text")
                        .HasColumnName("attributes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DefaultImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("default_image_url");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("numeric")
                        .HasColumnName("delivery_fee");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_currency");

                    b.Property<decimal>("DisplayPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("display_price");

                    b.Property<bool>("HasVariety")
                        .HasColumnType("boolean")
                        .HasColumnName("has_variety");

                    b.Property<string>("Images")
                        .HasColumnType("text")
                        .HasColumnName("images");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsOriginalImage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_original_image");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("PriceRange")
                        .HasColumnType("text")
                        .HasColumnName("price_range");

                    b.Property<decimal>("PriceWithDeliveryFee")
                        .HasColumnType("numeric")
                        .HasColumnName("price_with_delivery_fee");

                    b.Property<string>("RawImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("raw_image_url");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SearchTags")
                        .HasColumnType("text")
                        .HasColumnName("search_tags");

                    b.Property<string>("SearchTagsAutoGenerated")
                        .HasColumnType("text")
                        .HasColumnName("search_tags_auto_generated");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<string>("StationId")
                        .HasColumnType("text")
                        .HasColumnName("station_id");

                    b.Property<string>("SummaryDescription")
                        .HasColumnType("text")
                        .HasColumnName("summary_description");

                    b.Property<decimal?>("SupplierPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("supplier_price");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<decimal?>("WasDisplayPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("was_display_price");

                    b.Property<string>("ZoneId")
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_item");

                    b.HasIndex("ItemType")
                        .HasDatabaseName("ix_inventory_item_item_type");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_inventory_item_owner_id");

                    b.ToTable("inventory_item", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryItemPromotion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<int>("DiscountInPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("discount_in_percentage");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<string>("InventoryItemIds")
                        .HasColumnType("jsonb")
                        .HasColumnName("inventory_item_ids");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAppliedToItems")
                        .HasColumnType("boolean")
                        .HasColumnName("is_applied_to_items");

                    b.Property<bool>("IsAppliedToMenu")
                        .HasColumnType("boolean")
                        .HasColumnName("is_applied_to_menu");

                    b.Property<bool>("IsFreeDelivery")
                        .HasColumnType("boolean")
                        .HasColumnName("is_free_delivery");

                    b.Property<string>("MenuIds")
                        .HasColumnType("jsonb")
                        .HasColumnName("menu_ids");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_item_promotion");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_inventory_item_promotion_owner_id");

                    b.ToTable("inventory_item_promotion", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id")
                        .HasName("pk_inventory_outbox");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_outbox_unprocessed")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("inventory_outbox", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryReadModel", b =>
                {
                    b.Property<decimal?>("AdditionalDeliveryFee")
                        .HasColumnType("numeric")
                        .HasColumnName("additional_delivery_fee");

                    b.Property<string>("AdditionalDeliveryFeeDescription")
                        .HasColumnType("text")
                        .HasColumnName("additional_delivery_fee_description");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("numeric")
                        .HasColumnName("delivery_fee");

                    b.Property<string>("DisplayCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_currency");

                    b.Property<decimal>("DisplayPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("display_price");

                    b.Property<string>("DisplayTimes")
                        .HasColumnType("text")
                        .HasColumnName("display_times");

                    b.Property<bool>("HasDeals")
                        .HasColumnType("boolean")
                        .HasColumnName("has_deals");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsOriginalImage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_original_image");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("OldSellingPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("old_selling_price");

                    b.Property<string>("OpeningDayHours")
                        .HasColumnType("text")
                        .HasColumnName("opening_day_hours");

                    b.Property<bool>("OutOfStock")
                        .HasColumnType("boolean")
                        .HasColumnName("out_of_stock");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerImage")
                        .HasColumnType("text")
                        .HasColumnName("owner_image");

                    b.Property<string>("OwnerName")
                        .HasColumnType("text")
                        .HasColumnName("owner_name");

                    b.Property<string>("PriceRange")
                        .HasColumnType("text")
                        .HasColumnName("price_range");

                    b.Property<decimal>("PriceWithDeliveryFee")
                        .HasColumnType("numeric")
                        .HasColumnName("price_with_delivery_fee");

                    b.Property<string>("RawImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("raw_image_url");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<string>("StationId")
                        .HasColumnType("text")
                        .HasColumnName("station_id");

                    b.Property<decimal?>("SupplierPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("supplier_price");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<string>("Variety")
                        .HasColumnType("text")
                        .HasColumnName("variety");

                    b.Property<string>("ZoneId")
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.ToTable((string)null);

                    b.ToView("inventory_view", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Menu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_currency");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("InventoryItemIds")
                        .HasColumnType("jsonb")
                        .HasColumnName("inventory_item_ids");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<bool>("IsScheduled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_scheduled");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_menu");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_menu_owner_id");

                    b.ToTable("menu", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.MenuHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("MenuId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("menu_id");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_menu_history");

                    b.HasIndex("MenuId")
                        .HasDatabaseName("ix_menu_history_menu_id");

                    b.ToTable("menu_history", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.MenuReadModel", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("text")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryName")
                        .HasColumnType("text")
                        .HasColumnName("category_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_currency");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<bool>("IsScheduled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_scheduled");

                    b.Property<string>("ItemsJson")
                        .HasColumnType("text")
                        .HasColumnName("items_json");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerImage")
                        .HasColumnType("text")
                        .HasColumnName("owner_image");

                    b.Property<string>("OwnerName")
                        .HasColumnType("text")
                        .HasColumnName("owner_name");

                    b.Property<string>("PriceRange")
                        .HasColumnType("text")
                        .HasColumnName("price_range");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ToTable((string)null);

                    b.ToView("menu_view", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Pharmacy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_pharmacies");

                    b.ToTable("pharmacies", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Restaurant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_restaurants");

                    b.ToTable("restaurants", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Shop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_shops");

                    b.ToTable("shops", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Timetable", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Openings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("openings");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_timetable");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_timetable_owner_id");

                    b.ToTable("timetable", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Variety", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InventoryItemIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("inventory_item_ids");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Varieties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("varieties");

                    b.HasKey("Id")
                        .HasName("pk_variety");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_variety_owner_id");

                    b.ToTable("variety", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryAvailability", b =>
                {
                    b.HasOne("Inventory.API.Data.Entities.InventoryItem", "Item")
                        .WithOne("Availability")
                        .HasForeignKey("Inventory.API.Data.Entities.InventoryAvailability", "InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_availability_inventory_item_inventory_item_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryItem", b =>
                {
                    b.Navigation("Availability");
                });
#pragma warning restore 612, 618
        }
    }
}
