// <auto-generated />
using System;
using System.Collections.Generic;
using Inventory.API.Data;
using Inventory.API.Data.Entities;
using Inventory.Contracts.ReadModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventory.API.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260413122839_RenameOwnerIdToRetailerIdAddDisplayTimesAndRetailerType")]
    partial class RenameOwnerIdToRetailerIdAddDisplayTimesAndRetailerType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inventory.API.Data.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("AggregateId")
                        .HasDatabaseName("ix_audit_log_aggregate_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_log_occurred_at");

                    b.HasIndex("OutboxId")
                        .IsUnique()
                        .HasDatabaseName("ix_audit_log_outbox_id");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Branch", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AccountManager")
                        .HasColumnType("text")
                        .HasColumnName("account_manager");

                    b.Property<string>("ActivePaymentMethod")
                        .HasColumnType("text")
                        .HasColumnName("active_payment_method");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AutoSweepAccount")
                        .HasColumnType("text")
                        .HasColumnName("auto_sweep_account");

                    b.Property<bool>("AutoSweepEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_sweep_enabled");

                    b.Property<string>("BusinessEmail")
                        .HasColumnType("text")
                        .HasColumnName("business_email");

                    b.Property<string>("BusinessName")
                        .HasColumnType("text")
                        .HasColumnName("business_name");

                    b.Property<string>("BusinessPhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("business_phone_number");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("classification");

                    b.Property<string>("ColorCode")
                        .HasColumnType("text")
                        .HasColumnName("color_code");

                    b.Property<decimal>("CommissionFlat")
                        .HasColumnType("numeric")
                        .HasColumnName("commission_flat");

                    b.Property<decimal>("CommissionPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("commission_percentage");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string[]>("Cuisines")
                        .HasColumnType("text[]")
                        .HasColumnName("cuisines");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("numeric")
                        .HasColumnName("delivery_fee");

                    b.Property<string>("DisplayImage")
                        .HasColumnType("text")
                        .HasColumnName("display_image");

                    b.Property<List<DisplayTime>>("DisplayTimes")
                        .HasColumnType("jsonb")
                        .HasColumnName("display_times");

                    b.Property<string>("FineractAccountId")
                        .HasColumnType("text")
                        .HasColumnName("fineract_account_id");

                    b.Property<string>("FineractClientId")
                        .HasColumnType("text")
                        .HasColumnName("fineract_client_id");

                    b.Property<string>("FineractCommissionAccountId")
                        .HasColumnType("text")
                        .HasColumnName("fineract_commission_account_id");

                    b.Property<bool?>("HasAirCondition")
                        .HasColumnType("boolean")
                        .HasColumnName("has_air_condition");

                    b.Property<bool>("HasCommissionServices")
                        .HasColumnType("boolean")
                        .HasColumnName("has_commission_services");

                    b.Property<bool?>("HasPharmacistOnStandby")
                        .HasColumnType("boolean")
                        .HasColumnName("has_pharmacist_on_standby");

                    b.Property<bool>("HasRiderPayout")
                        .HasColumnType("boolean")
                        .HasColumnName("has_rider_payout");

                    b.Property<bool>("HasTakePayment")
                        .HasColumnType("boolean")
                        .HasColumnName("has_take_payment");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFranchise")
                        .HasColumnType("boolean")
                        .HasColumnName("is_franchise");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<bool>("IsReadyToServe")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ready_to_serve");

                    b.Property<bool>("IsSetupOnPortal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_setup_on_portal");

                    b.Property<bool>("IsSubscribedToReadyToOpenNotification")
                        .HasColumnType("boolean")
                        .HasColumnName("is_subscribed_to_ready_to_open_notification");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_updated_by");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationName")
                        .HasColumnType("text")
                        .HasColumnName("location_name");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MainStation")
                        .HasColumnType("text")
                        .HasColumnName("main_station");

                    b.Property<string>("MainStationId")
                        .HasColumnType("text")
                        .HasColumnName("main_station_id");

                    b.Property<List<string>>("MealTypes")
                        .HasColumnType("jsonb")
                        .HasColumnName("meal_types");

                    b.Property<List<RetailerOpeningDayHour>>("OpeningDayHours")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("opening_day_hours");

                    b.Property<List<PaymentMethod>>("PaymentMethods")
                        .HasColumnType("jsonb")
                        .HasColumnName("payment_methods");

                    b.Property<bool>("PermanentlyClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("permanently_closed");

                    b.Property<PaymentMethod>("PreferredPaymentMethods")
                        .HasColumnType("jsonb")
                        .HasColumnName("preferred_payment_methods");

                    b.Property<string>("RawImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("raw_image_url");

                    b.Property<List<string>>("RestaurantImages")
                        .HasColumnType("jsonb")
                        .HasColumnName("restaurant_images");

                    b.Property<string>("RestaurantType")
                        .HasColumnType("text")
                        .HasColumnName("restaurant_type");

                    b.Property<string>("RetailerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retailer_id");

                    b.Property<string>("RetailerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retailer_type");

                    b.Property<decimal>("RiderPayoutAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("rider_payout_amount");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<List<string>>("SearchTerms")
                        .HasColumnType("jsonb")
                        .HasColumnName("search_terms");

                    b.Property<decimal?>("ServiceCharge")
                        .HasColumnType("numeric")
                        .HasColumnName("service_charge");

                    b.Property<decimal>("ServiceMarkup")
                        .HasColumnType("numeric")
                        .HasColumnName("service_markup");

                    b.Property<string>("ServiceMarkupNotes")
                        .HasColumnType("text")
                        .HasColumnName("service_markup_notes");

                    b.Property<List<string>>("Stations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stations");

                    b.Property<List<string>>("StationsIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stations_ids");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<bool>("TemporaryClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("temporary_closed");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Zone")
                        .HasColumnType("text")
                        .HasColumnName("zone");

                    b.Property<string>("ZoneId")
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.HasIndex("RetailerId")
                        .HasDatabaseName("ix_branches_retailer_id");

                    b.HasIndex("RetailerType")
                        .HasDatabaseName("ix_branches_retailer_type");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.BranchReadModel", b =>
                {
                    b.Property<string>("AccountManager")
                        .HasColumnType("text")
                        .HasColumnName("account_manager");

                    b.Property<string>("ActivePaymentMethod")
                        .HasColumnType("text")
                        .HasColumnName("active_payment_method");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AutoSweepAccount")
                        .HasColumnType("text")
                        .HasColumnName("auto_sweep_account");

                    b.Property<bool>("AutoSweepEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_sweep_enabled");

                    b.Property<string>("BusinessEmail")
                        .HasColumnType("text")
                        .HasColumnName("business_email");

                    b.Property<string>("BusinessName")
                        .HasColumnType("text")
                        .HasColumnName("business_name");

                    b.Property<string>("BusinessPhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("business_phone_number");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("classification");

                    b.Property<string>("ColorCode")
                        .HasColumnType("text")
                        .HasColumnName("color_code");

                    b.Property<decimal>("CommissionFlat")
                        .HasColumnType("numeric")
                        .HasColumnName("commission_flat");

                    b.Property<decimal>("CommissionPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("commission_percentage");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string[]>("Cuisines")
                        .HasColumnType("text[]")
                        .HasColumnName("cuisines");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("numeric")
                        .HasColumnName("delivery_fee");

                    b.Property<string>("DisplayImage")
                        .HasColumnType("text")
                        .HasColumnName("display_image");

                    b.Property<string>("DisplayTimes")
                        .HasColumnType("text")
                        .HasColumnName("display_times");

                    b.Property<string>("FineractAccountId")
                        .HasColumnType("text")
                        .HasColumnName("fineract_account_id");

                    b.Property<string>("FineractClientId")
                        .HasColumnType("text")
                        .HasColumnName("fineract_client_id");

                    b.Property<string>("FineractCommissionAccountId")
                        .HasColumnType("text")
                        .HasColumnName("fineract_commission_account_id");

                    b.Property<bool?>("HasAirCondition")
                        .HasColumnType("boolean")
                        .HasColumnName("has_air_condition");

                    b.Property<bool>("HasCommissionServices")
                        .HasColumnType("boolean")
                        .HasColumnName("has_commission_services");

                    b.Property<bool?>("HasPharmacistOnStandby")
                        .HasColumnType("boolean")
                        .HasColumnName("has_pharmacist_on_standby");

                    b.Property<bool>("HasRiderPayout")
                        .HasColumnType("boolean")
                        .HasColumnName("has_rider_payout");

                    b.Property<bool>("HasTakePayment")
                        .HasColumnType("boolean")
                        .HasColumnName("has_take_payment");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFranchise")
                        .HasColumnType("boolean")
                        .HasColumnName("is_franchise");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<bool>("IsReadyToServe")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ready_to_serve");

                    b.Property<bool>("IsSetupOnPortal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_setup_on_portal");

                    b.Property<bool>("IsSubscribedToReadyToOpenNotification")
                        .HasColumnType("boolean")
                        .HasColumnName("is_subscribed_to_ready_to_open_notification");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationName")
                        .HasColumnType("text")
                        .HasColumnName("location_name");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MainStation")
                        .HasColumnType("text")
                        .HasColumnName("main_station");

                    b.Property<string>("MainStationId")
                        .HasColumnType("text")
                        .HasColumnName("main_station_id");

                    b.Property<string>("MealTypes")
                        .HasColumnType("text")
                        .HasColumnName("meal_types");

                    b.Property<string>("OpeningDayHours")
                        .HasColumnType("text")
                        .HasColumnName("opening_day_hours");

                    b.Property<string>("PaymentMethods")
                        .HasColumnType("text")
                        .HasColumnName("payment_methods");

                    b.Property<bool>("PermanentlyClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("permanently_closed");

                    b.Property<string>("PreferredPaymentMethods")
                        .HasColumnType("text")
                        .HasColumnName("preferred_payment_methods");

                    b.Property<string>("RawImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("raw_image_url");

                    b.Property<string>("RestaurantImages")
                        .HasColumnType("text")
                        .HasColumnName("restaurant_images");

                    b.Property<string>("RestaurantType")
                        .HasColumnType("text")
                        .HasColumnName("restaurant_type");

                    b.Property<string>("RetailerBusinessName")
                        .HasColumnType("text")
                        .HasColumnName("retailer_business_name");

                    b.Property<string>("RetailerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retailer_id");

                    b.Property<string>("RetailerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retailer_type");

                    b.Property<decimal>("RiderPayoutAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("rider_payout_amount");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("text")
                        .HasColumnName("search_terms");

                    b.Property<decimal?>("ServiceCharge")
                        .HasColumnType("numeric")
                        .HasColumnName("service_charge");

                    b.Property<decimal>("ServiceMarkup")
                        .HasColumnType("numeric")
                        .HasColumnName("service_markup");

                    b.Property<string>("ServiceMarkupNotes")
                        .HasColumnType("text")
                        .HasColumnName("service_markup_notes");

                    b.Property<string>("Stations")
                        .HasColumnType("text")
                        .HasColumnName("stations");

                    b.Property<string>("StationsIds")
                        .HasColumnType("text")
                        .HasColumnName("stations_ids");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<bool>("TemporaryClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("temporary_closed");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Zone")
                        .HasColumnType("text")
                        .HasColumnName("zone");

                    b.Property<string>("ZoneId")
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.ToTable((string)null);

                    b.ToView("branch_view", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_category_owner_id");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Attributes")
                        .HasColumnType("text")
                        .HasColumnName("attributes");

                    b.Property<int?>("AveragePreparationTime")
                        .HasColumnType("integer")
                        .HasColumnName("average_preparation_time");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DefaultImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("default_image_url");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("numeric")
                        .HasColumnName("delivery_fee");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_currency");

                    b.Property<decimal>("DisplayPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("display_price");

                    b.Property<List<InventoryOpeningHours>>("DisplayTimes")
                        .HasColumnType("jsonb")
                        .HasColumnName("display_times");

                    b.Property<bool>("HasDeals")
                        .HasColumnType("boolean")
                        .HasColumnName("has_deals");

                    b.Property<bool>("HasVariety")
                        .HasColumnType("boolean")
                        .HasColumnName("has_variety");

                    b.Property<string>("Images")
                        .HasColumnType("text")
                        .HasColumnName("images");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<bool>("IsOriginalImage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_original_image");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<List<InventoryOpeningHours>>("OpeningDayHours")
                        .HasColumnType("jsonb")
                        .HasColumnName("opening_day_hours");

                    b.Property<bool>("OutOfStock")
                        .HasColumnType("boolean")
                        .HasColumnName("out_of_stock");

                    b.Property<string>("PriceRange")
                        .HasColumnType("text")
                        .HasColumnName("price_range");

                    b.Property<string>("RawImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("raw_image_url");

                    b.Property<string>("RetailerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retailer_id");

                    b.Property<string>("RetailerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retailer_type");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<bool>("ScheduleAhead")
                        .HasColumnType("boolean")
                        .HasColumnName("schedule_ahead");

                    b.Property<string>("SearchTags")
                        .HasColumnType("text")
                        .HasColumnName("search_tags");

                    b.Property<string>("SearchTagsAutoGenerated")
                        .HasColumnType("text")
                        .HasColumnName("search_tags_auto_generated");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<string>("StationId")
                        .HasColumnType("text")
                        .HasColumnName("station_id");

                    b.Property<string>("SummaryDescription")
                        .HasColumnType("text")
                        .HasColumnName("summary_description");

                    b.Property<decimal?>("SupplierPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("supplier_price");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<decimal?>("WasDisplayPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("was_display_price");

                    b.Property<string>("ZoneId")
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_item");

                    b.HasIndex("ItemType")
                        .HasDatabaseName("ix_inventory_item_item_type");

                    b.HasIndex("RetailerId")
                        .HasDatabaseName("ix_inventory_item_retailer_id");

                    b.ToTable("inventory_item", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryItemPromotion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<int>("DiscountInPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("discount_in_percentage");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<string>("InventoryItemIds")
                        .HasColumnType("jsonb")
                        .HasColumnName("inventory_item_ids");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAppliedToItems")
                        .HasColumnType("boolean")
                        .HasColumnName("is_applied_to_items");

                    b.Property<bool>("IsAppliedToMenu")
                        .HasColumnType("boolean")
                        .HasColumnName("is_applied_to_menu");

                    b.Property<bool>("IsFreeDelivery")
                        .HasColumnType("boolean")
                        .HasColumnName("is_free_delivery");

                    b.Property<string>("MenuIds")
                        .HasColumnType("jsonb")
                        .HasColumnName("menu_ids");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_item_promotion");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_inventory_item_promotion_owner_id");

                    b.ToTable("inventory_item_promotion", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id")
                        .HasName("pk_inventory_outbox");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_outbox_unprocessed")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("inventory_outbox", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryReadModel", b =>
                {
                    b.Property<int?>("AveragePreparationTime")
                        .HasColumnType("integer")
                        .HasColumnName("average_preparation_time");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("numeric")
                        .HasColumnName("delivery_fee");

                    b.Property<string>("DisplayCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_currency");

                    b.Property<decimal>("DisplayPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("display_price");

                    b.Property<List<InventoryOpeningHours>>("DisplayTimes")
                        .HasColumnType("jsonb")
                        .HasColumnName("display_times");

                    b.Property<bool>("HasDeals")
                        .HasColumnType("boolean")
                        .HasColumnName("has_deals");

                    b.Property<bool>("HasVariety")
                        .HasColumnType("boolean")
                        .HasColumnName("has_variety");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsOriginalImage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_original_image");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("OldSellingPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("old_selling_price");

                    b.Property<List<InventoryOpeningHours>>("OpeningDayHours")
                        .HasColumnType("jsonb")
                        .HasColumnName("opening_day_hours");

                    b.Property<bool>("OutOfStock")
                        .HasColumnType("boolean")
                        .HasColumnName("out_of_stock");

                    b.Property<string>("PriceRange")
                        .HasColumnType("text")
                        .HasColumnName("price_range");

                    b.Property<string>("RawImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("raw_image_url");

                    b.Property<string>("RetailerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retailer_id");

                    b.Property<string>("RetailerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retailer_type");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<string>("StationId")
                        .HasColumnType("text")
                        .HasColumnName("station_id");

                    b.Property<decimal?>("SupplierPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("supplier_price");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<string>("Variety")
                        .HasColumnType("text")
                        .HasColumnName("variety");

                    b.Property<string>("ZoneId")
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.ToTable((string)null);

                    b.ToView("inventory_view", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Menu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_currency");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<List<MenuInventory>>("InventoryItemIds")
                        .HasColumnType("jsonb")
                        .HasColumnName("inventory_item_ids");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<bool>("IsScheduled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_scheduled");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_menu");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_menu_owner_id");

                    b.ToTable("menu", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.MenuHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("MenuId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("menu_id");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_menu_history");

                    b.HasIndex("MenuId")
                        .HasDatabaseName("ix_menu_history_menu_id");

                    b.ToTable("menu_history", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.MenuReadModel", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("text")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryName")
                        .HasColumnType("text")
                        .HasColumnName("category_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_currency");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<bool>("IsScheduled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_scheduled");

                    b.Property<string>("ItemsJson")
                        .HasColumnType("text")
                        .HasColumnName("items_json");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerImage")
                        .HasColumnType("text")
                        .HasColumnName("owner_image");

                    b.Property<string>("OwnerName")
                        .HasColumnType("text")
                        .HasColumnName("owner_name");

                    b.Property<string>("PriceRange")
                        .HasColumnType("text")
                        .HasColumnName("price_range");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ToTable((string)null);

                    b.ToView("menu_view", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Pharmacy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_pharmacies");

                    b.ToTable("pharmacies", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Restaurant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_restaurants");

                    b.ToTable("restaurants", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Retailer", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AccountManager")
                        .HasColumnType("text")
                        .HasColumnName("account_manager");

                    b.Property<string>("ActivePaymentMethod")
                        .HasColumnType("text")
                        .HasColumnName("active_payment_method");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AutoSweepAccount")
                        .HasColumnType("text")
                        .HasColumnName("auto_sweep_account");

                    b.Property<bool>("AutoSweepEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_sweep_enabled");

                    b.Property<string>("BusinessEmail")
                        .HasColumnType("text")
                        .HasColumnName("business_email");

                    b.Property<string>("BusinessName")
                        .HasColumnType("text")
                        .HasColumnName("business_name");

                    b.Property<string>("BusinessPhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("business_phone_number");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("classification");

                    b.Property<string>("ColorCode")
                        .HasColumnType("text")
                        .HasColumnName("color_code");

                    b.Property<decimal>("CommissionFlat")
                        .HasColumnType("numeric")
                        .HasColumnName("commission_flat");

                    b.Property<decimal>("CommissionPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("commission_percentage");

                    b.Property<string>("ComplianceId")
                        .HasColumnType("text")
                        .HasColumnName("compliance_id");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string[]>("Cuisines")
                        .HasColumnType("text[]")
                        .HasColumnName("cuisines");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("numeric")
                        .HasColumnName("delivery_fee");

                    b.Property<string>("DisplayImage")
                        .HasColumnType("text")
                        .HasColumnName("display_image");

                    b.Property<List<DisplayTime>>("DisplayTimes")
                        .HasColumnType("jsonb")
                        .HasColumnName("display_times");

                    b.Property<string>("FineractAccountId")
                        .HasColumnType("text")
                        .HasColumnName("fineract_account_id");

                    b.Property<string>("FineractClientId")
                        .HasColumnType("text")
                        .HasColumnName("fineract_client_id");

                    b.Property<string>("FineractCommissionAccountId")
                        .HasColumnType("text")
                        .HasColumnName("fineract_commission_account_id");

                    b.Property<bool?>("HasAirCondition")
                        .HasColumnType("boolean")
                        .HasColumnName("has_air_condition");

                    b.Property<bool>("HasCommissionServices")
                        .HasColumnType("boolean")
                        .HasColumnName("has_commission_services");

                    b.Property<bool?>("HasPharmacistOnStandby")
                        .HasColumnType("boolean")
                        .HasColumnName("has_pharmacist_on_standby");

                    b.Property<bool>("HasRiderPayout")
                        .HasColumnType("boolean")
                        .HasColumnName("has_rider_payout");

                    b.Property<bool>("HasTakePayment")
                        .HasColumnType("boolean")
                        .HasColumnName("has_take_payment");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFranchise")
                        .HasColumnType("boolean")
                        .HasColumnName("is_franchise");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<bool>("IsReadyToServe")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ready_to_serve");

                    b.Property<bool>("IsSetupOnPortal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_setup_on_portal");

                    b.Property<bool>("IsSubscribedToReadyToOpenNotification")
                        .HasColumnType("boolean")
                        .HasColumnName("is_subscribed_to_ready_to_open_notification");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_updated_by");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationName")
                        .HasColumnType("text")
                        .HasColumnName("location_name");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MainStation")
                        .HasColumnType("text")
                        .HasColumnName("main_station");

                    b.Property<string>("MainStationId")
                        .HasColumnType("text")
                        .HasColumnName("main_station_id");

                    b.Property<List<string>>("MealPackaging")
                        .HasColumnType("jsonb")
                        .HasColumnName("meal_packaging");

                    b.Property<List<string>>("MealTypes")
                        .HasColumnType("jsonb")
                        .HasColumnName("meal_types");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<List<RetailerOpeningDayHour>>("OpeningDayHours")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("opening_day_hours");

                    b.Property<List<OrderTelephoneNumber>>("OrderTelephoneNumbers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("order_telephone_numbers");

                    b.Property<List<PaymentMethod>>("PaymentMethods")
                        .HasColumnType("jsonb")
                        .HasColumnName("payment_methods");

                    b.Property<bool>("PermanentlyClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("permanently_closed");

                    b.Property<PaymentMethod>("PreferredPaymentMethods")
                        .HasColumnType("jsonb")
                        .HasColumnName("preferred_payment_methods");

                    b.Property<List<string>>("PreparationStyle")
                        .HasColumnType("jsonb")
                        .HasColumnName("preparation_style");

                    b.Property<string>("RawImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("raw_image_url");

                    b.Property<List<string>>("RestaurantImages")
                        .HasColumnType("jsonb")
                        .HasColumnName("restaurant_images");

                    b.Property<string>("RestaurantType")
                        .HasColumnType("text")
                        .HasColumnName("restaurant_type");

                    b.Property<List<RetailerAgreement>>("RetailerAgreement")
                        .HasColumnType("jsonb")
                        .HasColumnName("retailer_agreement");

                    b.Property<string>("RetailerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retailer_type");

                    b.Property<decimal>("RiderPayoutAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("rider_payout_amount");

                    b.Property<List<string>>("SearchTerms")
                        .HasColumnType("jsonb")
                        .HasColumnName("search_terms");

                    b.Property<decimal?>("ServiceCharge")
                        .HasColumnType("numeric")
                        .HasColumnName("service_charge");

                    b.Property<decimal>("ServiceMarkup")
                        .HasColumnType("numeric")
                        .HasColumnName("service_markup");

                    b.Property<string>("ServiceMarkupNotes")
                        .HasColumnType("text")
                        .HasColumnName("service_markup_notes");

                    b.Property<List<SocialMediaLink>>("SocialMediaLinks")
                        .HasColumnType("jsonb")
                        .HasColumnName("social_media_links");

                    b.Property<List<string>>("Stations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stations");

                    b.Property<List<string>>("StationsIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stations_ids");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<bool>("TemporaryClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("temporary_closed");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Zone")
                        .HasColumnType("text")
                        .HasColumnName("zone");

                    b.Property<string>("ZoneId")
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_retailers");

                    b.HasIndex("RetailerType")
                        .HasDatabaseName("ix_retailers_retailer_type");

                    b.ToTable("retailers", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Shop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_shops");

                    b.ToTable("shops", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Timetable", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Openings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("openings");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_timetable");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_timetable_owner_id");

                    b.ToTable("timetable", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Variety", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InventoryItemIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("inventory_item_ids");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<List<VarietyData>>("Varieties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("varieties");

                    b.HasKey("Id")
                        .HasName("pk_variety");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_variety_owner_id");

                    b.ToTable("variety", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
