// <auto-generated />
using System;
using Inventory.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventory.API.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260408040545_AddMenus")]
    partial class AddMenus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inventory.API.Data.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("AggregateId")
                        .HasDatabaseName("ix_audit_log_aggregate_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_log_occurred_at");

                    b.HasIndex("OutboxId")
                        .IsUnique()
                        .HasDatabaseName("ix_audit_log_outbox_id");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryAvailability", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("DisplayTimes")
                        .HasColumnType("text")
                        .HasColumnName("display_times");

                    b.Property<string>("InventoryItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inventory_item_id");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<string>("OpeningDayHours")
                        .HasColumnType("text")
                        .HasColumnName("opening_day_hours");

                    b.Property<bool>("OutOfStock")
                        .HasColumnType("boolean")
                        .HasColumnName("out_of_stock");

                    b.Property<DateTimeOffset?>("OutOfStockUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("out_of_stock_updated_at");

                    b.Property<string>("OutOfStockUpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("out_of_stock_updated_by");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<bool>("ScheduleAhead")
                        .HasColumnType("boolean")
                        .HasColumnName("schedule_ahead");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("stock_quantity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_inventory_availability");

                    b.HasIndex("InventoryItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_availability_inventory_item_id");

                    b.ToTable("inventory_availability", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal?>("AdditionalDeliveryFee")
                        .HasColumnType("numeric")
                        .HasColumnName("additional_delivery_fee");

                    b.Property<string>("AdditionalDeliveryFeeDescription")
                        .HasColumnType("text")
                        .HasColumnName("additional_delivery_fee_description");

                    b.Property<string>("Attributes")
                        .HasColumnType("text")
                        .HasColumnName("attributes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DefaultImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("default_image_url");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("numeric")
                        .HasColumnName("delivery_fee");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_currency");

                    b.Property<decimal>("DisplayPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("display_price");

                    b.Property<bool>("HasVariety")
                        .HasColumnType("boolean")
                        .HasColumnName("has_variety");

                    b.Property<string>("Images")
                        .HasColumnType("text")
                        .HasColumnName("images");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsOriginalImage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_original_image");

                    b.Property<bool>("IsVariety")
                        .HasColumnType("boolean")
                        .HasColumnName("is_variety");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("PriceRange")
                        .HasColumnType("text")
                        .HasColumnName("price_range");

                    b.Property<decimal>("PriceWithDeliveryFee")
                        .HasColumnType("numeric")
                        .HasColumnName("price_with_delivery_fee");

                    b.Property<string>("Promotion")
                        .HasColumnType("jsonb")
                        .HasColumnName("promotion");

                    b.Property<string>("RawImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("raw_image_url");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("SearchTags")
                        .HasColumnType("text")
                        .HasColumnName("search_tags");

                    b.Property<string>("SearchTagsAutoGenerated")
                        .HasColumnType("text")
                        .HasColumnName("search_tags_auto_generated");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<string>("StationId")
                        .HasColumnType("text")
                        .HasColumnName("station_id");

                    b.Property<string>("SummaryDescription")
                        .HasColumnType("text")
                        .HasColumnName("summary_description");

                    b.Property<decimal?>("SupplierPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("supplier_price");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("VarietyDifferentiator")
                        .HasColumnType("text")
                        .HasColumnName("variety_differentiator");

                    b.Property<string>("VarietyId")
                        .HasColumnType("text")
                        .HasColumnName("variety_id");

                    b.Property<decimal?>("WasDisplayPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("was_display_price");

                    b.Property<string>("ZoneId")
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_item");

                    b.HasIndex("ItemType")
                        .HasDatabaseName("ix_inventory_item_item_type");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_inventory_item_owner_id");

                    b.ToTable("inventory_item", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryItemPromotion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_amount");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<string>("InventoryItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inventory_item_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id")
                        .HasName("pk_inventory_item_promotion");

                    b.HasIndex("InventoryItemId")
                        .HasDatabaseName("ix_inventory_item_promotion_inventory_item_id");

                    b.ToTable("inventory_item_promotion", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id")
                        .HasName("pk_inventory_outbox");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_outbox_unprocessed")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("inventory_outbox", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryReadModel", b =>
                {
                    b.Property<decimal?>("AdditionalDeliveryFee")
                        .HasColumnType("numeric")
                        .HasColumnName("additional_delivery_fee");

                    b.Property<string>("AdditionalDeliveryFeeDescription")
                        .HasColumnType("text")
                        .HasColumnName("additional_delivery_fee_description");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision")
                        .HasColumnName("average_rating");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("numeric")
                        .HasColumnName("delivery_fee");

                    b.Property<string>("DisplayCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_currency");

                    b.Property<decimal>("DisplayPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("display_price");

                    b.Property<string>("DisplayTimes")
                        .HasColumnType("text")
                        .HasColumnName("display_times");

                    b.Property<bool>("HasDeals")
                        .HasColumnType("boolean")
                        .HasColumnName("has_deals");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsOriginalImage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_original_image");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("OldSellingPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("old_selling_price");

                    b.Property<string>("OpeningDayHours")
                        .HasColumnType("text")
                        .HasColumnName("opening_day_hours");

                    b.Property<bool>("OutOfStock")
                        .HasColumnType("boolean")
                        .HasColumnName("out_of_stock");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerImage")
                        .HasColumnType("text")
                        .HasColumnName("owner_image");

                    b.Property<string>("OwnerName")
                        .HasColumnType("text")
                        .HasColumnName("owner_name");

                    b.Property<string>("PriceRange")
                        .HasColumnType("text")
                        .HasColumnName("price_range");

                    b.Property<decimal>("PriceWithDeliveryFee")
                        .HasColumnType("numeric")
                        .HasColumnName("price_with_delivery_fee");

                    b.Property<string>("RawImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("raw_image_url");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<string>("StationId")
                        .HasColumnType("text")
                        .HasColumnName("station_id");

                    b.Property<decimal?>("SupplierPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("supplier_price");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("integer")
                        .HasColumnName("total_orders");

                    b.Property<int>("TotalRatingsCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_ratings_count");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer")
                        .HasColumnName("view_count");

                    b.Property<string>("ZoneId")
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.ToTable((string)null);

                    b.ToView("inventory_view", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryStats", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision")
                        .HasColumnName("average_rating");

                    b.Property<string>("AverageRatingDescription")
                        .HasColumnType("text")
                        .HasColumnName("average_rating_description");

                    b.Property<int>("CartCount")
                        .HasColumnType("integer")
                        .HasColumnName("cart_count");

                    b.Property<string>("InventoryItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inventory_item_id");

                    b.Property<int>("NumberShared")
                        .HasColumnType("integer")
                        .HasColumnName("number_shared");

                    b.Property<int>("SearchCount")
                        .HasColumnType("integer")
                        .HasColumnName("search_count");

                    b.Property<int>("SoldCount")
                        .HasColumnType("integer")
                        .HasColumnName("sold_count");

                    b.Property<int>("TotalRatingsCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_ratings_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer")
                        .HasColumnName("view_count");

                    b.HasKey("Id")
                        .HasName("pk_inventory_stats");

                    b.HasIndex("InventoryItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_stats_inventory_item_id");

                    b.ToTable("inventory_stats", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Menu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_menu");

                    b.HasIndex("ItemType")
                        .HasDatabaseName("ix_menu_item_type");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_menu_owner_id");

                    b.ToTable("menu", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.MenuItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("InventoryItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inventory_item_id");

                    b.Property<string>("MenuId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("menu_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_menu_item");

                    b.HasIndex("InventoryItemId")
                        .HasDatabaseName("ix_menu_item_inventory_item_id");

                    b.HasIndex("MenuId")
                        .HasDatabaseName("ix_menu_item_menu_id");

                    b.ToTable("menu_item", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.MenuReadModel", b =>
                {
                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision")
                        .HasColumnName("average_rating");

                    b.Property<string>("AverageRatingDescription")
                        .HasColumnType("text")
                        .HasColumnName("average_rating_description");

                    b.Property<int>("CartCount")
                        .HasColumnType("integer")
                        .HasColumnName("cart_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("item_count");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_type");

                    b.Property<string>("ItemsJson")
                        .HasColumnType("text")
                        .HasColumnName("items_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("NumberShared")
                        .HasColumnType("integer")
                        .HasColumnName("number_shared");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerImage")
                        .HasColumnType("text")
                        .HasColumnName("owner_image");

                    b.Property<string>("OwnerName")
                        .HasColumnType("text")
                        .HasColumnName("owner_name");

                    b.Property<int>("SearchCount")
                        .HasColumnType("integer")
                        .HasColumnName("search_count");

                    b.Property<int>("SoldCount")
                        .HasColumnType("integer")
                        .HasColumnName("sold_count");

                    b.Property<int>("TotalRatingsCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_ratings_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer")
                        .HasColumnName("view_count");

                    b.ToTable((string)null);

                    b.ToView("menu_view", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.MenuStats", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision")
                        .HasColumnName("average_rating");

                    b.Property<string>("AverageRatingDescription")
                        .HasColumnType("text")
                        .HasColumnName("average_rating_description");

                    b.Property<int>("CartCount")
                        .HasColumnType("integer")
                        .HasColumnName("cart_count");

                    b.Property<string>("MenuId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("menu_id");

                    b.Property<int>("NumberShared")
                        .HasColumnType("integer")
                        .HasColumnName("number_shared");

                    b.Property<int>("SearchCount")
                        .HasColumnType("integer")
                        .HasColumnName("search_count");

                    b.Property<int>("SoldCount")
                        .HasColumnType("integer")
                        .HasColumnName("sold_count");

                    b.Property<int>("TotalRatingsCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_ratings_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer")
                        .HasColumnName("view_count");

                    b.HasKey("Id")
                        .HasName("pk_menu_stats");

                    b.HasIndex("MenuId")
                        .IsUnique()
                        .HasDatabaseName("ix_menu_stats_menu_id");

                    b.ToTable("menu_stats", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Pharmacy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_pharmacies");

                    b.ToTable("pharmacies", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Restaurant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_restaurants");

                    b.ToTable("restaurants", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Shop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_shops");

                    b.ToTable("shops", (string)null);
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryAvailability", b =>
                {
                    b.HasOne("Inventory.API.Data.Entities.InventoryItem", "Item")
                        .WithOne("Availability")
                        .HasForeignKey("Inventory.API.Data.Entities.InventoryAvailability", "InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_availability_inventory_item_inventory_item_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryItemPromotion", b =>
                {
                    b.HasOne("Inventory.API.Data.Entities.InventoryItem", "Item")
                        .WithMany("Promotions")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_item_promotion_inventory_item_inventory_item_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryStats", b =>
                {
                    b.HasOne("Inventory.API.Data.Entities.InventoryItem", "Item")
                        .WithOne("Stats")
                        .HasForeignKey("Inventory.API.Data.Entities.InventoryStats", "InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_stats_inventory_items_inventory_item_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.MenuItem", b =>
                {
                    b.HasOne("Inventory.API.Data.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_item_inventory_item_inventory_item_id");

                    b.HasOne("Inventory.API.Data.Entities.Menu", "Menu")
                        .WithMany("Items")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_item_menu_menu_id");

                    b.Navigation("InventoryItem");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.MenuStats", b =>
                {
                    b.HasOne("Inventory.API.Data.Entities.Menu", "Menu")
                        .WithOne("Stats")
                        .HasForeignKey("Inventory.API.Data.Entities.MenuStats", "MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_stats_menus_menu_id");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.InventoryItem", b =>
                {
                    b.Navigation("Availability");

                    b.Navigation("Promotions");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Inventory.API.Data.Entities.Menu", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
