using InventoryCore.RowVersion;

namespace Inventory.API.Data.Entities;

public sealed class InventoryItem : IRowVersioned
{
    public string Id { get; set; } = "";
    public string Name { get; set; } = "";
    public string? ShortName { get; set; }
    public string? Description { get; set; }
    public string? SummaryDescription { get; set; }
    public string? DefaultImageUrl { get; set; }
    public string? RawImageUrl { get; set; }
    public bool IsOriginalImage { get; set; }
    public string ItemType { get; set; } = "";
    public string? Tags { get; set; }
    public string? SearchTags { get; set; }
    public string? SearchTagsAutoGenerated { get; set; }
    public string? Notes { get; set; }
    public string RetailerId { get; set; } = "";
    public string RetailerType { get; set; } = "";
    public string? StationId { get; set; }
    public string? ZoneId { get; set; }
    public bool HasVariety { get; set; }
    public string? Attributes { get; set; }
    public string? Images { get; set; }

    public decimal DisplayPrice { get; set; }
    public decimal? WasDisplayPrice { get; set; }
    public decimal? SupplierPrice { get; set; }
    public decimal DeliveryFee { get; set; }
    public string DisplayCurrency { get; set; } = "GHS";
    public string? PriceRange { get; set; }
    public int? AveragePreparationTime { get; set; }

    public bool IsAvailable { get; set; } = true;
    public bool OutOfStock { get; set; }
    public bool IsHidden { get; set; }
    public bool ScheduleAhead { get; set; }
    public List<Inventory.Contracts.ReadModel.InventoryOpeningHours>? OpeningDayHours { get; set; }
    public List<Inventory.Contracts.ReadModel.InventoryOpeningHours>? DisplayTimes { get; set; }

    public bool HasDeals { get; set; }
    public string? InventoryItemCode { get; set; }

    public bool IsDeleted { get; set; }
    public DateTimeOffset? DeletedAt { get; set; }
    public string? DeletedBy { get; set; }
    public DateTimeOffset CreatedAt { get; set; }
    public string? CreatedBy { get; set; }
    public DateTimeOffset UpdatedAt { get; set; }
    public string? UpdatedBy { get; set; }
    public long RowVersion { get; set; }
}
